import type { AffixDef, ItemBaseDef, UniqueDef } from './types.ts';

// Item bases, the affix pool, and Phase 1 uniques. The affix engine (tiers gated
// by item level, weighted) is the core of the loot chase (GDD §7). Phase 2
// expands the pool toward ~120 and adds crafting.

export const ITEM_BASES: ItemBaseDef[] = [
  {
    id: 'wpn_iron_greatsword',
    name: 'Iron Greatsword',
    slot: 'weapon',
    classReq: 'sentinel',
    levelReq: 1,
    icon: 'item_greatsword',
    weaponDamage: { min: 8, max: 14 },
    weaponDamageType: 'physical',
    implicits: [{ stat: 'damage', mode: 'inc', value: 0.08 }],
    tags: ['weapon', 'melee', 'str'],
  },
  {
    id: 'wpn_ashen_maul',
    name: 'Ashen Maul',
    slot: 'weapon',
    classReq: 'sentinel',
    levelReq: 5,
    icon: 'item_maul',
    weaponDamage: { min: 13, max: 22 },
    weaponDamageType: 'physical',
    implicits: [{ stat: 'critMulti', mode: 'flat', value: 0.15 }],
    tags: ['weapon', 'melee', 'str'],
  },
  {
    id: 'off_bulwark_shield',
    name: 'Bulwark Shield',
    slot: 'offhand',
    classReq: 'sentinel',
    levelReq: 1,
    icon: 'item_shield',
    implicits: [{ stat: 'block', mode: 'flat', value: 0.1 }],
    tags: ['shield', 'str'],
  },
  {
    id: 'helm_iron',
    name: 'Iron Helm',
    slot: 'helm',
    levelReq: 1,
    icon: 'item_helm',
    implicits: [{ stat: 'armor', mode: 'flat', value: 12 }],
    tags: ['armor'],
  },
  {
    id: 'chest_plate',
    name: 'Battered Cuirass',
    slot: 'chest',
    levelReq: 1,
    icon: 'item_chest',
    implicits: [{ stat: 'armor', mode: 'flat', value: 24 }],
    tags: ['armor'],
  },
  {
    id: 'gloves_leather',
    name: 'Worn Gauntlets',
    slot: 'gloves',
    levelReq: 1,
    icon: 'item_gloves',
    implicits: [{ stat: 'armor', mode: 'flat', value: 8 }],
    tags: ['armor'],
  },
  {
    id: 'boots_leather',
    name: 'Marching Boots',
    slot: 'boots',
    levelReq: 1,
    icon: 'item_boots',
    implicits: [{ stat: 'moveSpeed', mode: 'inc', value: 0.05 }],
    tags: ['armor'],
  },
  {
    id: 'belt_hide',
    name: 'Hide Belt',
    slot: 'belt',
    levelReq: 1,
    icon: 'item_belt',
    implicits: [{ stat: 'life', mode: 'flat', value: 12 }],
    tags: ['armor'],
  },
  {
    id: 'ring_band',
    name: 'Copper Band',
    slot: 'ring',
    levelReq: 1,
    icon: 'item_ring',
    implicits: [{ stat: 'allResist', mode: 'flat', value: 0.04 }],
    tags: ['jewellery'],
  },
  {
    id: 'amulet_talisman',
    name: 'Bone Talisman',
    slot: 'amulet',
    levelReq: 1,
    icon: 'item_amulet',
    implicits: [{ stat: 'life', mode: 'flat', value: 8 }],
    tags: ['jewellery'],
  },
];

const ARMOR_SLOTS: AffixDef['slots'] = ['helm', 'chest', 'gloves', 'boots', 'belt'];
const ALL_SLOTS: AffixDef['slots'] = [
  'helm',
  'chest',
  'gloves',
  'boots',
  'belt',
  'ring',
  'amulet',
  'weapon',
  'offhand',
];

export const AFFIXES: AffixDef[] = [
  // ---- Prefixes ----
  {
    id: 'p_life',
    name: 'of the Bear', // display suffix-style but kind prefix per data; name shown contextually
    kind: 'prefix',
    stat: 'life',
    mode: 'flat',
    slots: [...ARMOR_SLOTS, 'amulet'],
    tags: ['life', 'defence'],
    tiers: [
      { tier: 3, ilvl: 1, min: 10, max: 18, weight: 100 },
      { tier: 2, ilvl: 5, min: 18, max: 30, weight: 70 },
      { tier: 1, ilvl: 10, min: 30, max: 48, weight: 40 },
    ],
  },
  {
    id: 'p_armor',
    name: 'Plated',
    kind: 'prefix',
    stat: 'armor',
    mode: 'flat',
    slots: ARMOR_SLOTS,
    tags: ['defence'],
    tiers: [
      { tier: 3, ilvl: 1, min: 10, max: 20, weight: 100 },
      { tier: 2, ilvl: 5, min: 20, max: 38, weight: 70 },
      { tier: 1, ilvl: 10, min: 38, max: 60, weight: 40 },
    ],
  },
  {
    id: 'p_phys_dmg',
    name: 'Honed',
    kind: 'prefix',
    stat: 'damage',
    mode: 'inc',
    slots: ['weapon'],
    tags: ['damage', 'str'],
    tiers: [
      { tier: 3, ilvl: 1, min: 0.1, max: 0.18, weight: 100 },
      { tier: 2, ilvl: 5, min: 0.18, max: 0.28, weight: 70 },
      { tier: 1, ilvl: 10, min: 0.28, max: 0.42, weight: 40 },
    ],
  },
  {
    id: 'p_thorns',
    name: 'Barbed',
    kind: 'prefix',
    stat: 'thorns',
    mode: 'flat',
    slots: ['chest', 'offhand', 'gloves'],
    tags: ['defence'],
    tiers: [
      { tier: 2, ilvl: 1, min: 2, max: 5, weight: 60 },
      { tier: 1, ilvl: 8, min: 5, max: 10, weight: 35 },
    ],
  },
  {
    id: 'p_lifeonhit',
    name: 'Bloodletting',
    kind: 'prefix',
    stat: 'lifeOnHit',
    mode: 'flat',
    slots: ['weapon', 'gloves', 'ring'],
    tags: ['life', 'damage'],
    tiers: [
      { tier: 2, ilvl: 3, min: 1, max: 2, weight: 60 },
      { tier: 1, ilvl: 9, min: 2, max: 4, weight: 35 },
    ],
  },
  // ---- Suffixes ----
  {
    id: 's_allres',
    name: 'of Warding',
    kind: 'suffix',
    stat: 'allResist',
    mode: 'flat',
    slots: ['ring', 'amulet', 'chest', 'belt'],
    tags: ['resist', 'defence'],
    tiers: [
      { tier: 3, ilvl: 1, min: 0.05, max: 0.09, weight: 90 },
      { tier: 2, ilvl: 6, min: 0.09, max: 0.14, weight: 60 },
      { tier: 1, ilvl: 11, min: 0.14, max: 0.2, weight: 30 },
    ],
  },
  {
    id: 's_fireres',
    name: 'of the Ember',
    kind: 'suffix',
    stat: 'resistFire',
    mode: 'flat',
    slots: ALL_SLOTS,
    tags: ['resist'],
    tiers: [
      { tier: 3, ilvl: 1, min: 0.1, max: 0.16, weight: 100 },
      { tier: 2, ilvl: 6, min: 0.16, max: 0.26, weight: 60 },
      { tier: 1, ilvl: 11, min: 0.26, max: 0.4, weight: 30 },
    ],
  },
  {
    id: 's_might',
    name: 'of Might',
    kind: 'suffix',
    stat: 'might',
    mode: 'flat',
    slots: ALL_SLOTS,
    tags: ['attribute', 'str'],
    tiers: [
      { tier: 3, ilvl: 1, min: 3, max: 6, weight: 90 },
      { tier: 2, ilvl: 6, min: 6, max: 10, weight: 60 },
      { tier: 1, ilvl: 11, min: 10, max: 16, weight: 30 },
    ],
  },
  {
    id: 's_vitality',
    name: 'of Vigor',
    kind: 'suffix',
    stat: 'vitality',
    mode: 'flat',
    slots: ALL_SLOTS,
    tags: ['attribute', 'life'],
    tiers: [
      { tier: 3, ilvl: 1, min: 3, max: 6, weight: 90 },
      { tier: 2, ilvl: 6, min: 6, max: 10, weight: 60 },
      { tier: 1, ilvl: 11, min: 10, max: 16, weight: 30 },
    ],
  },
  {
    id: 's_precision',
    name: 'of Precision',
    kind: 'suffix',
    stat: 'precision',
    mode: 'flat',
    slots: ALL_SLOTS,
    tags: ['attribute', 'crit'],
    tiers: [
      { tier: 3, ilvl: 1, min: 3, max: 6, weight: 80 },
      { tier: 2, ilvl: 6, min: 6, max: 10, weight: 55 },
      { tier: 1, ilvl: 11, min: 10, max: 16, weight: 28 },
    ],
  },
  {
    id: 's_critchance',
    name: 'of Ruin',
    kind: 'suffix',
    stat: 'critChance',
    mode: 'flat',
    slots: ['weapon', 'ring', 'amulet', 'gloves'],
    tags: ['crit', 'damage'],
    tiers: [
      { tier: 2, ilvl: 3, min: 0.02, max: 0.035, weight: 60 },
      { tier: 1, ilvl: 9, min: 0.035, max: 0.06, weight: 30 },
    ],
  },
  {
    id: 's_attackspeed',
    name: 'of Swiftness',
    kind: 'suffix',
    stat: 'attackSpeed',
    mode: 'inc',
    slots: ['weapon', 'gloves', 'ring'],
    tags: ['speed', 'damage'],
    tiers: [
      { tier: 2, ilvl: 3, min: 0.05, max: 0.09, weight: 60 },
      { tier: 1, ilvl: 9, min: 0.09, max: 0.15, weight: 30 },
    ],
  },
  {
    id: 's_movespeed',
    name: 'of the Wind',
    kind: 'suffix',
    stat: 'moveSpeed',
    mode: 'inc',
    slots: ['boots'],
    tags: ['speed'],
    tiers: [
      { tier: 3, ilvl: 1, min: 0.08, max: 0.12, weight: 100 },
      { tier: 2, ilvl: 6, min: 0.12, max: 0.18, weight: 55 },
      { tier: 1, ilvl: 11, min: 0.18, max: 0.25, weight: 26 },
    ],
  },
];

export const UNIQUES: UniqueDef[] = [
  {
    id: 'uniq_emberfall_oath',
    name: 'Emberfall Oath',
    baseId: 'wpn_iron_greatsword',
    rarity: 'unique',
    icon: 'item_greatsword_unique',
    flavor: '"Hold the line. Even when the line is ash."',
    levelReq: 4,
    fixedMods: [
      { stat: 'damage', mode: 'inc', value: 0.35 },
      { stat: 'might', mode: 'flat', value: 12 },
      { stat: 'lifeOnHit', mode: 'flat', value: 3 },
    ],
    rulesText: ['Cleave scorches the ground it sweeps.', '+35% increased damage', 'Leeches life on hit'],
  },
  {
    id: 'uniq_last_lantern',
    name: 'The Last Lantern',
    baseId: 'amulet_talisman',
    rarity: 'unique',
    icon: 'item_amulet_unique',
    flavor: '"While one lantern burns, the dark has not won."',
    levelReq: 3,
    fixedMods: [
      { stat: 'life', mode: 'flat', value: 30 },
      { stat: 'resistFire', mode: 'flat', value: 0.3 },
      { stat: 'lifeRegen', mode: 'flat', value: 4 },
    ],
    rulesText: ['You cannot be Ignited.', '+30 Life', '+30% Fire Resistance', 'Regenerate life steadily'],
  },
  {
    id: 'uniq_gatewardens_grief',
    name: "Gatewarden's Grief",
    baseId: 'belt_hide',
    rarity: 'unique',
    icon: 'item_belt_unique',
    flavor: '"He guards it still, though the gate is only memory."',
    levelReq: 6,
    fixedMods: [
      { stat: 'life', mode: 'flat', value: 40 },
      { stat: 'armor', mode: 'flat', value: 40 },
      { stat: 'allResist', mode: 'flat', value: 0.08 },
    ],
    rulesText: ['Take 10% less damage while surrounded.', '+40 Life', '+40 Armor', '+8% All Resistance'],
  },
];
