import type { BossDef, MonsterDef } from './types.ts';

// Emberfall Reach bestiary: six monster types across the Riven and Ashborn Cult
// families (GDD §8), plus the act-region boss. Balance via tools/sim-bench.

export const MONSTERS: MonsterDef[] = [
  {
    id: 'riven_wretch',
    name: 'Riven Wretch',
    family: 'riven',
    rank: 'normal',
    archetype: 'swarm',
    level: 1,
    life: 16,
    lifePerLevel: 3,
    armor: 4,
    resist: { physical: 0.05 },
    moveSpeed: 4.6,
    colliderRadius: 0.34,
    height: 1.1,
    aggroRange: 10,
    leashRange: 22,
    preferredRange: 0,
    attackSkillId: 'swarm_bite',
    xp: 6,
    lootTableId: 'loot_trash',
    goldMin: 0,
    goldMax: 3,
    modelKind: 'riven',
    modelVariant: 'wretch',
    tint: 0x8a5a3c,
    scale: 0.8,
  },
  {
    id: 'riven_husk',
    name: 'Riven Husk',
    family: 'riven',
    rank: 'normal',
    archetype: 'melee',
    level: 2,
    life: 34,
    lifePerLevel: 6,
    armor: 10,
    resist: { physical: 0.1 },
    moveSpeed: 3.8,
    colliderRadius: 0.45,
    height: 1.7,
    aggroRange: 10,
    leashRange: 24,
    preferredRange: 0,
    attackSkillId: 'riven_claw',
    xp: 17,
    lootTableId: 'loot_common',
    goldMin: 1,
    goldMax: 6,
    modelKind: 'riven',
    modelVariant: 'husk',
    tint: 0x6b4a34,
    scale: 1,
  },
  {
    id: 'riven_stalker',
    name: 'Riven Stalker',
    family: 'riven',
    rank: 'normal',
    archetype: 'melee',
    level: 3,
    life: 28,
    lifePerLevel: 6,
    armor: 8,
    resist: {},
    moveSpeed: 5.4,
    colliderRadius: 0.4,
    height: 1.6,
    aggroRange: 12,
    leashRange: 26,
    preferredRange: 0,
    attackSkillId: 'riven_claw',
    xp: 13,
    lootTableId: 'loot_common',
    goldMin: 1,
    goldMax: 7,
    modelKind: 'riven',
    modelVariant: 'stalker',
    tint: 0x7a3d52,
    scale: 0.92,
  },
  {
    id: 'ashborn_zealot',
    name: 'Ashborn Zealot',
    family: 'ashborn',
    rank: 'normal',
    archetype: 'melee',
    level: 3,
    life: 40,
    lifePerLevel: 7,
    armor: 12,
    resist: { fire: 0.3 },
    moveSpeed: 3.9,
    colliderRadius: 0.45,
    height: 1.75,
    aggroRange: 11,
    leashRange: 24,
    preferredRange: 0,
    attackSkillId: 'riven_claw',
    xp: 12,
    lootTableId: 'loot_common',
    goldMin: 2,
    goldMax: 9,
    modelKind: 'ashborn',
    modelVariant: 'zealot',
    tint: 0x9c3b28,
    scale: 1.02,
  },
  {
    id: 'ashborn_pyre',
    name: 'Ashborn Pyremonger',
    family: 'ashborn',
    rank: 'normal',
    archetype: 'ranged',
    level: 4,
    life: 30,
    lifePerLevel: 6,
    armor: 8,
    resist: { fire: 0.5 },
    moveSpeed: 3.4,
    colliderRadius: 0.44,
    height: 1.75,
    aggroRange: 14,
    leashRange: 26,
    preferredRange: 9,
    attackSkillId: 'ashborn_bolt',
    xp: 20,
    lootTableId: 'loot_common',
    goldMin: 2,
    goldMax: 10,
    modelKind: 'ashborn',
    modelVariant: 'pyre',
    tint: 0xc85a2a,
    scale: 1,
  },
  {
    id: 'riven_brute',
    name: 'Riven Brute',
    family: 'riven',
    rank: 'normal',
    archetype: 'brute',
    level: 5,
    life: 96,
    lifePerLevel: 14,
    armor: 20,
    resist: { physical: 0.15 },
    moveSpeed: 3.2,
    colliderRadius: 0.7,
    height: 2.4,
    aggroRange: 11,
    leashRange: 26,
    preferredRange: 0,
    attackSkillId: 'husk_smash',
    xp: 45,
    lootTableId: 'loot_elite',
    goldMin: 6,
    goldMax: 18,
    modelKind: 'riven',
    modelVariant: 'brute',
    tint: 0x5a3a2c,
    scale: 1.5,
  },
];

export const BOSSES: BossDef[] = [
  {
    id: 'warden_broken_gate',
    name: 'Vorthak',
    title: 'Warden of the Broken Gate',
    family: 'riven',
    rank: 'boss',
    archetype: 'brute',
    level: 7,
    life: 820,
    lifePerLevel: 60,
    armor: 30,
    resist: { physical: 0.2, fire: 0.25 },
    moveSpeed: 3.4,
    colliderRadius: 1.4,
    height: 3.6,
    aggroRange: 30,
    leashRange: 60,
    preferredRange: 0,
    attackSkillId: 'gate_cleave',
    xp: 300,
    lootTableId: 'loot_boss',
    goldMin: 40,
    goldMax: 80,
    modelKind: 'boss',
    modelVariant: 'gatewarden',
    tint: 0x8c2f2f,
    scale: 1,
    introText: 'The gate was never meant to open. Vorthak makes sure it never closes.',
    phases: [
      {
        lifeFraction: 1,
        mechanicIntervalMs: 5200,
        mechanicSkillIds: ['gate_quake'],
        moveSpeedMult: 1,
        damageMult: 1,
      },
      {
        lifeFraction: 0.66,
        mechanicIntervalMs: 4200,
        mechanicSkillIds: ['gate_quake', 'gate_pyre'],
        moveSpeedMult: 1.1,
        damageMult: 1.1,
      },
      {
        lifeFraction: 0.33,
        mechanicIntervalMs: 3200,
        mechanicSkillIds: ['gate_pyre', 'gate_quake'],
        moveSpeedMult: 1.25,
        damageMult: 1.25,
      },
    ],
  },
];
