import type { SkillDef } from './types.ts';

// All Phase 1 skills: the Sentinel's six + monster/boss attacks. Numbers are
// balance knobs tuned via tools/sim-bench (GDD §4/§6). Timings are in ms; the
// skill system converts to ticks and (optionally) scales by attack speed.

export const SENTINEL_SKILLS: SkillDef[] = [
  {
    id: 'cleave',
    name: 'Cleave',
    classId: 'sentinel',
    description: 'A sweeping strike that carves through everything in front of you and stokes your Wrath.',
    icon: 'skill_cleave',
    tags: ['melee', 'area', 'strike', 'physical'],
    damageType: 'physical',
    base: { min: 12, max: 18 },
    perLevel: 0.09,
    resourceCost: -12, // generates Wrath
    cooldownMs: 0,
    windupMs: 90,
    recoveryMs: 190,
    scaleTimingWithHaste: true,
    aim: 'direction',
    effect: { type: 'meleeArc', range: 2.7, halfAngleDeg: 60, knockback: 0.3 },
    canCrit: true,
    hitStopMs: 40,
    vfx: 'slash_wide',
    sfx: 'sfx_cleave',
    minLevel: 1,
  },
  {
    id: 'shield_slam',
    name: 'Shield Slam',
    classId: 'sentinel',
    description: 'Bash a foe for heavy damage and a stun. Your answer to anything dangerous.',
    icon: 'skill_shield_slam',
    tags: ['melee', 'strike', 'physical'],
    damageType: 'physical',
    base: { min: 20, max: 30 },
    perLevel: 0.09,
    resourceCost: 15,
    cooldownMs: 3000,
    windupMs: 130,
    recoveryMs: 250,
    scaleTimingWithHaste: true,
    aim: 'direction',
    effect: { type: 'meleeArc', range: 2.3, halfAngleDeg: 35, knockback: 1.3, stunMs: 900 },
    canCrit: true,
    hitStopMs: 60,
    vfx: 'impact_slam',
    sfx: 'sfx_slam',
    minLevel: 2,
  },
  {
    id: 'whirl_charge',
    name: 'Whirl Charge',
    classId: 'sentinel',
    description: 'Spin forward through the enemy, gap-closing and slicing all in your path.',
    icon: 'skill_whirl_charge',
    tags: ['melee', 'area', 'movement', 'physical'],
    damageType: 'physical',
    base: { min: 14, max: 22 },
    perLevel: 0.09,
    resourceCost: 20,
    cooldownMs: 5000,
    windupMs: 50,
    recoveryMs: 180,
    scaleTimingWithHaste: false,
    aim: 'direction',
    effect: { type: 'dashStrike', distance: 6.5, radius: 1.9, knockback: 0.7 },
    canCrit: true,
    hitStopMs: 30,
    vfx: 'whirl_trail',
    sfx: 'sfx_whirl',
    minLevel: 3,
  },
  {
    id: 'warcry',
    name: 'Warcry',
    classId: 'sentinel',
    description: 'Roar defiance: enrage yourself, harden your armor, and force nearby foes to face you.',
    icon: 'skill_warcry',
    tags: ['buff'],
    damageType: 'physical',
    base: { min: 0, max: 0 },
    perLevel: 0,
    resourceCost: 25,
    cooldownMs: 9000,
    windupMs: 180,
    recoveryMs: 260,
    scaleTimingWithHaste: false,
    aim: 'self',
    effect: { type: 'buff', buffId: 'warcry_buff', radius: 6, taunt: true },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'warcry_ring',
    sfx: 'sfx_warcry',
    minLevel: 4,
  },
  {
    id: 'sunder',
    name: 'Sunder',
    classId: 'sentinel',
    description: 'Drive your weapon into the ground, splitting the earth in a line and shattering enemy armor.',
    icon: 'skill_sunder',
    tags: ['melee', 'area', 'physical'],
    damageType: 'physical',
    base: { min: 24, max: 36 },
    perLevel: 0.1,
    resourceCost: 30,
    cooldownMs: 6000,
    windupMs: 260,
    recoveryMs: 320,
    scaleTimingWithHaste: false,
    aim: 'direction',
    effect: { type: 'lineAoe', length: 7, width: 2.4, knockback: 0.4, debuffId: 'sunder_shred' },
    canCrit: true,
    hitStopMs: 55,
    vfx: 'earth_split',
    sfx: 'sfx_sunder',
    minLevel: 6,
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    classId: 'sentinel',
    description: 'Brace behind your guard. While planted you take far less damage and block reliably.',
    icon: 'skill_bulwark',
    tags: ['buff'],
    damageType: 'physical',
    base: { min: 0, max: 0 },
    perLevel: 0,
    resourceCost: -10,
    cooldownMs: 8000,
    windupMs: 70,
    recoveryMs: 120,
    scaleTimingWithHaste: false,
    aim: 'self',
    effect: { type: 'buff', buffId: 'bulwark_stance' },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'bulwark_aura',
    sfx: 'sfx_bulwark',
    minLevel: 5,
  },
];

export const MONSTER_SKILLS: SkillDef[] = [
  {
    id: 'riven_claw',
    name: 'Riven Claw',
    classId: 'monster',
    description: 'A raking swipe from torn talons.',
    icon: 'skill_generic',
    tags: ['melee', 'physical'],
    damageType: 'physical',
    base: { min: 5, max: 9 },
    perLevel: 0.11,
    resourceCost: 0,
    cooldownMs: 1200,
    windupMs: 300,
    recoveryMs: 320,
    scaleTimingWithHaste: false,
    aim: 'direction',
    effect: {
      type: 'meleeArc',
      range: 1.9,
      halfAngleDeg: 45,
      knockback: 0.2,
      ailment: { type: 'bleed', chance: 0.25, magnitude: 6, durationTicks: 90 },
    },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'slash_small',
    sfx: 'sfx_claw',
    minLevel: 1,
  },
  {
    id: 'husk_smash',
    name: 'Husk Smash',
    classId: 'monster',
    description: 'A heavy overhead slam. Telegraphed — get out of the way.',
    icon: 'skill_generic',
    tags: ['melee', 'physical'],
    damageType: 'physical',
    base: { min: 12, max: 18 },
    perLevel: 0.12,
    resourceCost: 0,
    cooldownMs: 2600,
    windupMs: 620,
    recoveryMs: 420,
    scaleTimingWithHaste: false,
    aim: 'direction',
    effect: { type: 'meleeArc', range: 2.4, halfAngleDeg: 40, knockback: 1.1, stunMs: 500 },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'impact_slam',
    sfx: 'sfx_smash',
    minLevel: 1,
  },
  {
    id: 'ashborn_bolt',
    name: 'Ashen Bolt',
    classId: 'monster',
    description: 'A bolt of cultist fire.',
    icon: 'skill_generic',
    tags: ['ranged', 'projectile', 'fire'],
    damageType: 'fire',
    base: { min: 7, max: 12 },
    perLevel: 0.11,
    resourceCost: 0,
    cooldownMs: 2400,
    windupMs: 520,
    recoveryMs: 380,
    scaleTimingWithHaste: false,
    aim: 'direction',
    effect: {
      type: 'projectile',
      speed: 13,
      radius: 0.45,
      range: 15,
      ailment: { type: 'ignite', chance: 0.3, magnitude: 10, durationTicks: 90 },
    },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'fire_bolt',
    sfx: 'sfx_firebolt',
    minLevel: 1,
  },
  {
    id: 'swarm_bite',
    name: 'Swarm Bite',
    classId: 'monster',
    description: 'A quick, darting bite.',
    icon: 'skill_generic',
    tags: ['melee', 'physical'],
    damageType: 'physical',
    base: { min: 3, max: 6 },
    perLevel: 0.1,
    resourceCost: 0,
    cooldownMs: 900,
    windupMs: 200,
    recoveryMs: 200,
    scaleTimingWithHaste: false,
    aim: 'direction',
    effect: { type: 'meleeArc', range: 1.5, halfAngleDeg: 55 },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'slash_small',
    sfx: 'sfx_bite',
    minLevel: 1,
  },
];

export const BOSS_SKILLS: SkillDef[] = [
  {
    id: 'gate_cleave',
    name: 'Gatebreaker Cleave',
    classId: 'monster',
    description: 'A massive sweeping blow.',
    icon: 'skill_generic',
    tags: ['melee', 'area', 'physical'],
    damageType: 'physical',
    base: { min: 16, max: 24 },
    perLevel: 0.12,
    resourceCost: 0,
    cooldownMs: 3200,
    windupMs: 640,
    recoveryMs: 480,
    scaleTimingWithHaste: false,
    aim: 'direction',
    effect: { type: 'meleeArc', range: 3.6, halfAngleDeg: 75, knockback: 1.4 },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'slash_wide',
    sfx: 'sfx_boss_cleave',
    minLevel: 1,
  },
  {
    id: 'gate_quake',
    name: 'Sundering Quake',
    classId: 'monster',
    description: 'Slams the ground, splitting a long fissure.',
    icon: 'skill_generic',
    tags: ['area', 'physical'],
    damageType: 'physical',
    base: { min: 20, max: 30 },
    perLevel: 0.12,
    resourceCost: 0,
    cooldownMs: 6000,
    windupMs: 900,
    recoveryMs: 620,
    scaleTimingWithHaste: false,
    aim: 'direction',
    effect: { type: 'lineAoe', length: 10, width: 3, knockback: 1.6, stunMs: 700 },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'earth_split',
    sfx: 'sfx_boss_quake',
    minLevel: 1,
  },
  {
    id: 'gate_pyre',
    name: 'Broken Pyre',
    classId: 'monster',
    description: 'Erupts a ring of unstable path-fire.',
    icon: 'skill_generic',
    tags: ['area', 'fire'],
    damageType: 'fire',
    base: { min: 14, max: 20 },
    perLevel: 0.12,
    resourceCost: 0,
    cooldownMs: 7000,
    windupMs: 700,
    recoveryMs: 520,
    scaleTimingWithHaste: false,
    aim: 'self',
    effect: {
      type: 'groundZone',
      radius: 5,
      durationMs: 4000,
      tickMs: 500,
      ailment: { type: 'ignite', chance: 0.6, magnitude: 14, durationTicks: 90 },
    },
    canCrit: false,
    hitStopMs: 0,
    vfx: 'fire_ring',
    sfx: 'sfx_boss_pyre',
    minLevel: 1,
  },
];

export const ALL_SKILLS: SkillDef[] = [...SENTINEL_SKILLS, ...MONSTER_SKILLS, ...BOSS_SKILLS];
